# Generated by Django 4.2.6 on 2023-10-13 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('number', models.CharField(max_length=20, verbose_name='Numero da conta')),
                ('agency', models.CharField(max_length=20, verbose_name='Agência')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('number_account', models.CharField(max_length=50, verbose_name='Numero da conta')),
                ('value', models.FloatField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Depositos',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('number_account_origin', models.CharField(max_length=50, verbose_name='Numero da conta')),
                ('number_account_destiny', models.CharField(max_length=50, verbose_name='Numero da conta')),
                ('value', models.FloatField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Transferências',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('number_account', models.CharField(max_length=50, verbose_name='Numero da conta')),
                ('value', models.FloatField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Saques',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Numero da Conta')),
                ('balance', models.FloatField(default=0, verbose_name='Saldo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'Contas',
            },
        ),
    ]
